version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: 
          Ref: TASK_DEFINITION_NAME
        LoadBalancerInfo:
          ContainerName: !Ref ECS_CONTAINER
          ContainerPort: 80 # Replace this with the actual container port used in your service.
