version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 942731209985.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t poc-repo .
      - docker tag poc-repo:latest 942731209985.dkr.ecr.ap-south-1.amazonaws.com/poc-repo:latest
      - docker images
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 942731209985.dkr.ecr.ap-south-1.amazonaws.com/poc-repo:latest
      - echo Build completed on `date`

